import ROOT
import math
import sys
import argparse
from plot_utility import *

#parser = argparse.ArgumentParser()
#parser.add_argument("year")
#args = parser.parse_args()

tree1 = ROOT.TChain("tree")
tree1.Add('/afs/cern.ch/user/f/fanx/EOS_space/HZg_AOD/pico/full_class_DY_redwood.root')

tree2 = ROOT.TChain("tree")

tree2.Add('sample/mixing_output_2016_redwood_refit.root')
tree2.Add('sample/mixing_output_2016APV_redwood_refit.root')
tree2.Add('sample/mixing_output_2017_redwood_refit.root')
tree2.Add('sample/mixing_output_2018_redwood_refit.root')

sample1 = "Drell-Yan Pile-up"
sample2 = "Mixing Events"

nEntries1 = tree1.GetEntries()
nEntries2 = tree2.GetEntries()

#pt = twoHist("pT", 130, 15, 80)
njet = twoHist("njet", 4, 2, 6, sample1, sample2)
dijet_deta = twoHist("dijet_deta", 50, 0, 5, sample1, sample2)
dijet_dphi = twoHist("dijet_dphi", 70, 0, 3.14, sample1, sample2)
dijet_mass = twoHist("dijet_mass", 80, 0, 800, sample1, sample2)

j1_pt = twoHist("pT(j1)", 50, 20, 200, sample1, sample2)
#j1_m = twoHist("m(j1)", 30, 0, 30, sample1, sample2)
j1_eta = twoHist("#eta(j1)", 50, -2.5, 2.5, sample1, sample2)
j2_pt = twoHist("pT(j2)", 50, 20, 200, sample1, sample2)
#j2_m = twoHist("m(j2)", 30, 0, 30, sample1, sample2)
j2_eta = twoHist("#eta(j2)", 50, -2.5, 2.5, sample1, sample2)
llphoton_dijet_balance =  twoHist("llphoton_dijet_balance", 100, 0, 1, sample1, sample2)
llphoton_dijet_dphi =  twoHist("llphoton_dijet_dphi", 70, 0, 3.14, sample1, sample2)
llphoton_psi = twoHist("llphoton_psi", 100, -5, 5, sample1, sample2)
min_dR = twoHist("min_dR", 70, 0.3, 3.5, sample1, sample2)
max_dR = twoHist("max_dR", 70, 0.5, 4, sample1, sample2)
costheta = twoHist("llphoton_cos(#theta)", 100, -1, 1, sample1, sample2)
cosTheta = twoHist("llphoton_cos(#Theta)", 100, -1, 1, sample1, sample2)
l1_eta = twoHist("#eta(l1)", 50, -2.5, 2.5, sample1, sample2)
l2_eta = twoHist("#eta(l2)", 50, -2.5, 2.5, sample1, sample2)
photon_eta = twoHist("#eta(#gamma)", 50, -2.5, 2.5, sample1, sample2)
photon_mva = twoHist("photon_idmva", 90, 0.1, 1, sample1, sample2)
photon_res = twoHist("photon_res", 80, 0, 0.2, sample1, sample2)
llphoton_pTt = twoHist("llphoton_pTt", 100, 10, 200, sample1, sample2)
photon_zeppenfeld =  twoHist("photon_zeppenfeld", 100, 0, 5, sample1, sample2)
photon_jet1_dr =  twoHist("photon_jet1_dr", 60, 0, 6, sample1, sample2)
photon_jet2_dr =  twoHist("photon_jet2_dr", 60, 0, 6, sample1, sample2)
rel_photon_pt = twoHist("Photon_relative_pT", 50, 0.1, 0.6, sample1, sample2)
dphi_llg_jj = twoHist("#Delta#phi(Z#gamma,dijet)", 35, 0, 3.5, sample1, sample2)
pt_mass = twoHist("pt_mass", 50, 0, 1, sample1, sample2)
llgpsi =  twoHist("llg_psi", 70, -3.14,3.14 , sample1, sample2)
dphi_hmiss_photon = twoHist("#Delta#phi(H_{miss},#gamma)", 32, 0, 3.2, sample1, sample2)

for i in range(nEntries1):
    tree1.GetEntry(i)
    if not (tree1.njet >= 2 and tree1.nbdfm == 0 and tree1.nlep == 2) or tree1.DY_class != 1: continue
    z = ROOT.TLorentzVector()
    g = ROOT.TLorentzVector()
    z.SetPtEtaPhiM(tree1.ll_pt, tree1.ll_eta, tree1.ll_phi, tree1.ll_m)
    g.SetPtEtaPhiM(tree1.photon_pt, tree1.photon_eta, tree1.photon_phi, 0)
    h = z + g
    h_pt = h.Vect()
    z_pt = z.Vect()
    g_pt = g.Vect()

    j1 = ROOT.TLorentzVector()
    j1.SetPtEtaPhiM(tree1.j1_pt, tree1.j1_eta, tree1.j1_phi, tree1.j1_m)
    j2 = ROOT.TLorentzVector()
    j2.SetPtEtaPhiM(tree1.j2_pt, tree1.j2_eta, tree1.j2_phi, tree1.j2_m)
    jj = j1 + j2
    dijet_mass.Fill1(jj.M(), tree1.weight)
    dphi_llg_jj.Fill1(h.DeltaPhi(jj), tree1.weight)
    j1_pt.Fill1(tree1.j1_pt, tree1.weight)
    j1_eta.Fill1(tree1.j1_eta, tree1.weight)
    j2_pt.Fill1(tree1.j2_pt, tree1.weight)
    j2_eta.Fill1(tree1.j2_eta, tree1.weight)
    dijet_deta.Fill1(abs(j1.Eta() - j2.Eta()), tree1.weight)
    dijet_dphi.Fill1(j1.DeltaPhi(j2), tree1.weight)
    photon_jet1_dr.Fill1(j1.DeltaR(g), tree1.weight)
    photon_jet2_dr.Fill1(j2.DeltaR(g), tree1.weight)
    photon_zeppenfeld.Fill1(abs(tree1.photon_eta - 0.5 * tree1.j1_eta - 0.5 * tree1.j2_eta), tree1.weight)
    rel_photon_pt.Fill1(tree1.photon_pt/tree1.llphoton_m, tree1.weight)
    photon_eta.Fill1(tree1.photon_eta, tree1.weight)
    l1_eta.Fill1(tree1.l1_eta, tree1.weight)
    l2_eta.Fill1(tree1.l2_eta, tree1.weight)
    llphoton_pTt.Fill1(h_pt.Cross((z_pt-g_pt).Unit()).Mag(), tree1.weight)
    photon_mva.Fill1(tree1.photon_idmva, tree1.weight)
    costheta.Fill1(tree1.llphoton_costheta, tree1.weight)
    cosTheta.Fill1(tree1.llphoton_cosTheta, tree1.weight)
    min_dR.Fill1(tree1.photon_drmin, tree1.weight)
    max_dR.Fill1(tree1.photon_drmax, tree1.weight)
    llgpsi.Fill1(tree1.llphoton_psi, tree1.weight)
    photon_res.Fill1(tree1.photon_energyErr/ROOT.TMath.CosH(tree1.photon_eta)/tree1.photon_pt, tree1.weight)
    pt_mass.Fill1(tree1.llphoton_pt/tree1.llphoton_m, tree1.weight)
    njet.Fill1(tree1.njet, tree1.weight)
    dphi_hmiss_photon.Fill1(dphi(abs(tree1.photon_phi - (-h - j1 - j2).Phi())), tree1.weight)
    
for j in range(nEntries2):
    tree2.GetEntry(j)
    if not (tree2.njet >= 2 and tree2.nbdfm == 0 and tree2.nel + tree2.nmu == 2 and tree2.llphoton_m[0] > 100 and tree2.llphoton_m[0] < 180): continue
    photon_eta.Fill2(tree2.photon_eta[0], tree2.weight * tree2.yr_weight)
    llphoton_pTt.Fill2(tree2.llphoton_pTt[0], tree2.weight * tree2.yr_weight)
    costheta.Fill2(tree2.llphoton_costheta[0], tree2.weight * tree2.yr_weight)
    cosTheta.Fill2(tree2.llphoton_cosTheta[0], tree2.weight * tree2.yr_weight)
    photon_mva.Fill2(tree2.photon_idmva[0], tree2.weight * tree2.yr_weight)
    min_dR.Fill2(tree2.photon_drmin[0], tree2.weight * tree2.yr_weight)
    max_dR.Fill2(tree2.photon_drmax[0], tree2.weight * tree2.yr_weight)
    if tree2.nel >= 2 and tree2.ll_lepid[0] == 11:
        l1_eta.Fill2(tree2.el_eta[tree2.ll_i1[0]], tree2.weight * tree2.yr_weight)
        l2_eta.Fill2(tree2.el_eta[tree2.ll_i2[0]], tree2.weight * tree2.yr_weight)
    elif tree2.nmu >= 2 and tree2.ll_lepid[0] == 13:
        l1_eta.Fill2(tree2.mu_eta[tree2.ll_i1[0]], tree2.weight * tree2.yr_weight)
        l2_eta.Fill2(tree2.mu_eta[tree2.ll_i2[0]], tree2.weight * tree2.yr_weight)
    llgpsi.Fill2(tree2.llphoton_psi[0], tree2.weight * tree2.yr_weight)
    photon_res.Fill2(tree2.photon_energyErr[0]/ROOT.TMath.CosH(tree2.photon_eta[0])/tree2.photon_pt[0], tree2.weight * tree2.yr_weight)
    pt_mass.Fill2(tree2.llphoton_pt[0]/tree2.llphoton_m[0], tree2.weight * tree2.yr_weight)
    njet.Fill2(tree2.njet, tree2.weight * tree2.yr_weight)
    h = ROOT.TLorentzVector()
    g = ROOT.TLorentzVector()
    #    h.SetPtEtaPhiM(tree2.llphoton_pt[0], tree1.ll_eta, tree1.ll_phi, tree1.ll_m)
    h.SetPtEtaPhiM(tree2.llphoton_pt[0], tree2.llphoton_eta[0], tree2.llphoton_phi[0], tree2.llphoton_m[0])
    Njet = 0
    j1 = ROOT.TLorentzVector()
    j2 = ROOT.TLorentzVector()
    for i, is_good in enumerate(tree2.jet_isgood):
        if is_good and Njet == 0:
            j1_pt.Fill2(tree2.jet_pt[i],  tree2.weight * tree2.yr_weight)
            j1_eta.Fill2(tree2.jet_eta[i],  tree2.weight * tree2.yr_weight)
            j1.SetPtEtaPhiM(tree2.jet_pt[i], tree2.jet_eta[i], tree2.jet_phi[i], tree2.jet_m[i])
            Njet += 1
        elif is_good and Njet == 1:
            j2_pt.Fill2(tree2.jet_pt[i],  tree2.weight * tree2.yr_weight)
            j2_eta.Fill2(tree2.jet_eta[i],  tree2.weight * tree2.yr_weight)
            j2.SetPtEtaPhiM(tree2.jet_pt[i], tree2.jet_eta[i], tree2.jet_phi[i], tree2.jet_m[i])
            Njet += 1
            break
    photon_zeppenfeld.Fill2(abs(tree2.photon_eta[0] - (j1.Eta() + j2.Eta())/2), tree2.weight * tree2.yr_weight)
    photon_jet1_dr.Fill2(j1.DeltaR(g), tree2.weight * tree2.yr_weight)
    photon_jet2_dr.Fill2(j2.DeltaR(g), tree2.weight * tree2.yr_weight)
    dijet_mass.Fill2(tree2.dijet_m, tree2.weight * tree2.yr_weight)
    dphi_llg_jj.Fill2(tree2.llphoton_dijet_dphi[0], tree2.weight * tree2.yr_weight)
    dijet_deta.Fill2(tree2.dijet_deta,  tree2.weight * tree2.yr_weight)
    dijet_dphi.Fill2(tree2.dijet_dphi,  tree2.weight * tree2.yr_weight)
    rel_photon_pt.Fill2(tree2.photon_pt[0]/tree2.llphoton_m[0], tree2.weight * tree2.yr_weight)
    dphi_hmiss_photon.Fill2(dphi(abs(tree2.photon_phi[0] - (-h - j1 - j2).Phi())), tree2.weight * tree2.yr_weight)
        #dphi_llg_j1.Fill2()

llphoton_pTt.makePlot('VBF_mix_run2')
costheta.makePlot('VBF_mix_run2')
cosTheta.makePlot('VBF_mix_run2')
photon_mva.makePlot('VBF_mix_run2')
min_dR.makePlot('VBF_mix_run2')
max_dR.makePlot('VBF_mix_run2')
l1_eta.makePlot('VBF_mix_run2')
l2_eta.makePlot('VBF_mix_run2')
llgpsi.makePlot('VBF_mix_run2')
photon_res.makePlot('VBF_mix_run2')
pt_mass.makePlot('VBF_mix_run2')
j1_pt.makePlot('VBF_mix_run2')
j1_eta.makePlot('VBF_mix_run2')
j2_pt.makePlot('VBF_mix_run2')
j2_eta.makePlot('VBF_mix_run2')
photon_eta.makePlot('VBF_mix_run2')
photon_jet1_dr.makePlot('VBF_mix_run2')
photon_jet2_dr.makePlot('VBF_mix_run2')
njet.makePlot('VBF_mix_run2')
photon_zeppenfeld.makePlot('VBF_mix_run2')
rel_photon_pt.makePlot('VBF_mix_run2')
dijet_deta.makePlot('VBF_mix_run2')
dijet_dphi.makePlot('VBF_mix_run2')
dijet_mass.makePlot('VBF_mix_run2')
dphi_llg_jj.makePlot('VBF_mix_run2')
dphi_hmiss_photon.makePlot('VBF_mix_run2')
